### ISSUE TITLE
極座標変換がおかしい

### ISSUE THREAD

**Issue by ePi5131** [ePi5131/patch.aul#23]
・極座標変換を使う(スクリプトを使う)と落ちる
・逆に遅くなる

などが散見される　これはなに？

**Comment by ePi5131** [comment]
あとそもそも計算式がおかしいらしいというのも見た　こーれ再解析です

**Comment by nazonoSAUNA** [comment]
トラック「渦巻」を使用した時に明らかにぼやけることを確認
-1周辺では一部欠損したり明らかに変になるのが確認できました

（再解析したプルリク中のやつは問題なさそうでした）

**Comment by ePi5131** [comment]
(多分)done
