### ISSUE TITLE
最新のVSでビルドができない

### ISSUE THREAD

**Issue by ePi5131** [ePi5131/patch.aul#35]
`operator""_fmt`が全滅している模様

https://godbolt.org/z/Gn8djxMW5 ざっくり検証したら古いmsvcではコンパイルできるが新しいものではできなくなってしまったらしい
私がC++規格に沿っていないコードを書いていてエラーになるようになったのか、msvcのバグを引いているのかはわからない

**Comment by hiraginoyuki** [comment]
https://github.com/ilammy/msvc-dev-cmd

**Comment by ePi5131** [comment]
https://godbolt.org/z/Traorqbq8 こういうことな気がしてきた

https://cpprefjp.github.io/reference/format/format.html
> 書式文字列は定数式でなければならず、その妥当性がコンパイル時にチェックされる。実行時に決まるフォーマット文字列を使用したい場合、[vformat](https://cpprefjp.github.io/reference/format/vformat.html)を使用できる。

**Comment by ePi5131** [comment]
そうだったね
