### ISSUE TITLE
不正なjson

### ISSUE THREAD

**Issue by halt76** [ePi5131/patch.aul#56]
patch.aul.json を削除 → aviutl を起動、何もせず終了 → aviutl を起動
で 100% 設定ファイルが不正と出ます。

theme_cc の項目を消すと正常に起動します。
ここのデータの読み込みが失敗するのが理由だと思うのですが。

**Comment by nazonoSAUNA** [comment]
@halt76 
https://github.com/ePi5131/patch.aul/issues/48
これではありませんか？

**Comment by halt76** [comment]
違いますね。
初回に値の無い json が書き出され、それに対応してない感じです。
そもそも theme_cc の部分の設定ってどこでやるんでしょうか。

**Comment by nazonoSAUNA** [comment]
@halt76 
値の無いjsonとはどのような状態でしょうか？
以下正常に作成されたjsonの中身の上の方です
```
{
	"console" : {
		"visible" : false
	},
	"theme_cc" : {
		"layer" : {
			"height_large" : 31,
			"height_medium" : 26,
			"height_small" : 22,
			"link_col" : "4040c0",
			"clipping_col" : "c04040",
			"lock_col" : [ "000000", "c04040" ],
			"hide_alpha" : 0.850000
		},
		"object" : {
			"media_col" : [ "10206c", "1830c0", "4080ff" ],
			"mfilter_col" : [ "106c10", "18c018", "40f040" ],
			"audio_col" : [ "6c1018", "c01820", "f83040" ],
			"afilter_col" : [ "6c6c10", "c0c020", "d8d840" ],
			"control_col" : [ "106c6c", "18c0c0", "40d8d8" ],
			"inactive_col" : [ "606060", "808080", "909090" ],
			"clipping_col" : "c04040",
			"clipping_height" : -3,
			"midpt_size" : [ 4, 3, 3 ],
			"name_col" : [ "ffffff", "a0a0a0" ]
		},
		"timeline" : {
			"scale_col" : [ "60a0ff", "204080" ],
			"bpm_grid_col" : [ "646464", "a0a0a0" ]
		}
	},
	"redo" : {
		"shift" : true
	},
```
theme_cc の項目を消す　というのは下のほうの　"switch" "theme_cc" : false,　としたということでしょうか?
上の方の "theme_cc" : { の中身をすべて削除したということでしょうか?

上の方の"theme_cc" : { の中身を一部だけ消していき、どこに原因があるかを確認していただければ幸いです

**Comment by halt76** [comment]
初回で書き出されるのはこうです。
色データが存在しないってことですね。

	"theme_cc" : {
		"layer" : {
			"link_col" : ,
			"clipping_col" : ,
			"lock_col" : 
		},
		"object" : {
			"media_col" : ,
			"mfilter_col" : ,
			"audio_col" : ,
			"afilter_col" : ,
			"control_col" : ,
			"inactive_col" : ,
			"clipping_col" : "000000",
			"name_col" : 
		},
		"timeline" : {
			"scale_col" : ,
			"bpm_grid_col" : 
		}
	}

**Comment by nazonoSAUNA** [comment]
@halt76 
原因が分かりましたありがとうございます
```
"switch" : {
		"access_key" : false,
		"colorpalette_cache" : true,
		"exo_aviutlfilter" : true,
		"exo_sceneidx" : true,
		"exo_trackparam" : true,
		"exo_track_minusval" : true,
		"exo_specialcolorconv" : true,
		"exa_fold_gui" : true,
		"tra_aviutlfilter" : true,
		"tra_change_drawfilter" : true,
		"tra_specified_speed" : true,
		"text_op_size" : true,
		"ignore_media_param_reset" : false,
		"failed_sjis_msgbox" : true,
		"theme_cc" : false,
		"exeditwindow_sizing" : true,
		"settingdialog_move" : true,
		"obj_colorcorrection" : true,
		"obj_lensblur" : true,
		"obj_noise" : true,
		"settingdialog_excolorconfig" : true,
		"r_click_menu_split" : true,
		"r_click_menu_delete" : true,
		"blend" : true,
		"add_extension" : true,
		"undo" : true,
		"undo.redo" : true,
		"console" : true,
		"console.escape" : true,
		"console.input" : false,
		"console.debug_string" : true,
		"console.debug_string.time" : true,
		"lua" : true,
		"lua.env" : false,
		"lua.path" : false,
		"lua.getvalue" : true,
		"lua.rand" : true,
		"lua.randex" : true,
		"fast" : true,
		"fast.exeditwindow" : true,
		"fast_settingdialog" : true,
		"fast.text" : true,
		"fast.create_figure" : true,
		"fast.border" : true,
		"fast.cl" : true,
		"fast.radiationalblur" : true,
		"fast.polortransform" : true,
		"fast.displacementmap" : true,
		"fast.flash" : true,
		"fast.directionalblur" : true,
		"fast.lensblur" : true
	}
```
下のほうにある"switch" "theme_cc" : false, となっている状態で上の方の中身を削除すると起こるようです
とりあえずはtrueにしてみてください

**Comment by halt76** [comment]
初回の書き出しで "theme_cc" : true ですけど。

**Comment by ePi5131** [comment]
バグ報告感謝します
修正をコミットしたので、ビルド環境があればお試しください

**Comment by nazonoSAUNA** [comment]
@halt76 
とりあえず上記修正によりjson不正のエラーは出なくなると思われますが、
"theme_cc" : false, 以外の原因で起こっている点が気になります。(theme_ccの機能が使えない状態になっていると思われます)

こちらで確認したところ他の条件ではexedit.aufのバージョン0.92が導入されていない
というのが確認されました。拡張編集は導入されていますか?

**Comment by halt76** [comment]
拡張編集は入れてないですね。
それが原因なんでしょうか。

@ePi5131
リリース待ってます。

**Comment by nazonoSAUNA** [comment]
@halt76
了解です。
拡張編集導入下でしか動作確認をしていないため気づけなかったバグということです

**Comment by halt76** [comment]
じゃあ修正はされたようなのでクローズしても大丈夫です。

**Comment by nazonoSAUNA** [comment]
リリースまでとりあえずですが
https://github.com/ePi5131/patch.aul/issues/56#issuecomment-1221270084
これをコピーして貼り付けることで起こらなくなるとは思います

**Comment by ePi5131** [comment]
とりあえずr42 beta1としてリリースしました

**Comment by ePi5131** [comment]
問題なさそうなのでクローズしてしまいます　まだ問題があればまた開けてください
