### ISSUE TITLE
+新規プロジェクト作成窓のテキストボックスのサイズを大きくする

### ISSUE THREAD

**Issue by ePi5131** [ePi5131/patch.aul#67]
**背景**
新規プロジェクトを作成 の画像サイズを指定するテキストボックスが短くて、Wine環境では3桁までしか入力できない
→1280x720などを指定できない
一時期Wine側が修正していたが最近再発するようになったらしい

**概要**
テキストボックスの長さを長くしてあげる
ダイアログリソース名は`NEW_FILE`なのでなんとかしてください

**その他**
0.93rc1ではサイレント修正でこれが広がって改善されたので0.92にも持ってくる

**Comment by pklion** [comment]
https://github.com/hebiiro/AviUtl-Plugin-BigDialog/ ?

**Comment by ePi5131** [comment]
これ終わってた
