### ISSUE TITLE
*画像ループフィルタの謎挙動

### ISSUE THREAD

**Issue by yak9909** [ePi5131/patch.aul#77]
**概要**
`個別オブジェクト` にチェックを入れた画像ループフィルタでオブジェクトを増殖させ、
その上に何かフィルタ効果を乗せると、そのフィルタが増殖するごとに付与されていく（？）
色調補正をかけて色相をいじると分かりやすいです

**再現手順**
1. オブジェクトに `画像ループ` フィルタを追加
2. `画像ループ` の `個別オブジェクト` にチェックを入れる
3. `縦` と `横` を任意の数増やす
4. 画像処理系のフィルタを追加 (ここでは色調補正を追加します)
5. 色相を変えるとエグいことになる

**起こってほしかったこと**
常に画像ループフィルタ付与前の画像で処理してほしい

**スクリーンショット**
![image](https://user-images.githubusercontent.com/40179392/203914840-12b66392-42a3-4ba2-bbd6-c7cde6250242.png)

**環境**
AviUtl version 1.10
拡張編集 version 0.92
↓その他プラグイン情報↓
![image](https://user-images.githubusercontent.com/40179392/203915064-08bdcf68-7c00-40f2-8946-0e3d62957585.png)

**Comment by nazonoSAUNA** [comment]
書かれている通り、描画ごとにエフェクトが追加されていくようになっていることを確認
元々のオブジェクトの状態を保存→描画ごとに復元を行っていないためにそのようになってしまっているようです
そのようなコードを追加することで修正することができました

**Comment by yak9909** [comment]
https://github.com/nazonoSAUNA/patch.aul/releases/tag/r43_1
にて、修正を確認できました。ありがとうございます
Issue閉じておきます
