### ISSUE TITLE
拡張編集との相性問題

### ISSUE THREAD

**Issue by renorari** [ePi5131/patch.aul#93]
**概要**
エラーメッセージ等なにも表示されずにクラッシュします。
patch.aulのコンソールウインドウが表示されるとこまでは進みますが、コンフィグなどのファイルが生成されません。

**再現手順**
AviUtlのv1.10と拡張編集のv0.92とpatch.aulのr42を組み合わせると引き起こされます。

**起こってほしかったこと**
正常に起動する 又は エラーログが生成される

**環境**
上記の通り、AviUtlと拡張編集とpatch.aulのみの環境でテストしました。

**その他**
突然使用不可になりました。
他のソフトウエアの影響が考えられます。

**Comment by renorari** [comment]
**追記**
Visual Studio installerにて、Visual Studio 2022の更新を行いました。

**Comment by nazonoSAUNA** [comment]
詳細の確認ですが、そのタイトルと説明からすると
AviUtlのv1.10　patch.aulのr42　ではクラッシュしない（この組み合わせで正常な場合jsonが生成される）
AviUtlのv1.10　拡張編集のv0.92　patch.aulのr41以前　ではクラッシュしない
ということで間違いないでしょうか?

**Comment by renorari** [comment]
> AviUtlのv1.10　patch.aulのr42　ではクラッシュしない（この組み合わせで正常な場合jsonが生成される）

はい、そうです。

> AviUtlのv1.10　拡張編集のv0.92　patch.aulのr41以前　ではクラッシュしない

r41でも同様のの不具合が発生しました。


ご確認ありがとうございます。

**Comment by nazonoSAUNA** [comment]
それでは生成されたjsonにて各機能をオフにしていき、どれが原因かを特定することは可能でしょうか?

**Comment by renorari** [comment]
わかりました。試してみます。

**Comment by renorari** [comment]
![image](https://user-images.githubusercontent.com/56919233/210149101-2645f52c-16b6-4fa4-98c0-8feaff6c45d5.png)
エラー画面がでました。
※1度のみ表示されましたので、今回の件に関連するかはわかりかねますが、万が一のためにアップロードしておきます。

**Comment by renorari** [comment]
結果が出ました...
fast機能が原因のようです。

**Comment by renorari** [comment]
さらに調べてみました。
fast.cl機能が主な原因のようです。

**Comment by renorari** [comment]
fast.clのみの無効化でクラッシュが起こらなくなりました。
エラーログなどは表示されていないので、詳細情報はわかりかねますが、patch.aulはとても重宝していますので、今後も機能改善をしていただけると幸いです。
何卒宜しくお願い致します。

**Comment by nazonoSAUNA** [comment]
#7 にあるr42.01ではどうでしょうか？
 また、今まで使えてたということからGPU・グラフィックボード関係で何か変わったことは無いかの確認はできますか?
 ドライバのアップデートや設定など

**Comment by renorari** [comment]
返信遅くなり申し訳ありません。
r42.01を試しましたが、r42, r41と変わらない結果でした。
グラフィック関係での変更やアップデートなどはありませんでした。
何卒宜しくお願い致します。

**Comment by nazonoSAUNA** [comment]
再現する環境もその他報告もないため、基本的にこちらから何かすることはできませんが、
突然使用不可になったその前後で何が変わったかを突き止める必要があるのではないかと思います。
アップデート関係も何もないのであれば例えばGPUが壊れたなどの可能性もありますね

**Comment by nazonoSAUNA** [comment]
とりあえずですが #7 と同じように各デバッグファイルにて動作確認してみて頂ければと思います

**Comment by renorari** [comment]
動作確認結果

1: ⭕
2: ❌
3: ⭕
4: ⭕
5: ❌
6: ❌
7: ❌
8: ❌

r41: ❌
r42: ❌
r42.01: ❌

r42(fast.clの無効化): ⭕

**Comment by renorari** [comment]
Windows: 
![image](https://user-images.githubusercontent.com/56919233/210198712-b1e84969-871c-4fa9-ae4a-96c04abb15c2.png)

**Comment by nazonoSAUNA** [comment]
https://drive.google.com/drive/folders/1S3C30qJqLXMRaqn1v3uFfmKx1_ft8SEY
以前作った実験用ファイルで、放射ブラーのGPU処理が行われます。
こちらでエラーは出るか、実際に高速化が行われているか確認できますか

**Comment by renorari** [comment]
エラーが発生しました。
![image](https://user-images.githubusercontent.com/56919233/210205434-c4470082-cde6-41ad-8a0c-cd24b60794ee.png)

**Comment by nazonoSAUNA** [comment]
そうなるとpatch.aul側に問題があるエラーではなさそうですね
kernelbase.dll エラー などで検索していろいろ試すしかないかもしれません。

**Comment by renorari** [comment]
なるほど。
丁寧な対応ありがとうございました。
